### ISSUE TITLE
trackGlobalErrors is not a function

### ISSUE THREAD

**Issue by tstehle** [infinitered/reactotron-react-native#13]
Since 3.x.x, for all versions, I get a crash at startup;
`(0, _reactotronReactNative.trackGlobalErrors) is not a function.`
when I do a `.use(trackGlobalErrors())`.

I import trackGlobalErrors normally: 
`import Reactotron, { trackGlobalErrors } from 'reactotron-react-native';`

Everything works fine in 2.2.0.

**Comment by rmevans9** [comment]
The individual plugins might have got lost in the rewrite. Can you try this for now?

```
Reactotron.useReactNative({ 
  errors: {}
  editor: false
  overlay: false
  asyncStorage: false
  networking: false
  storybook: false
})
```

I will work to get the individual plugins re-established as exports.

**Comment by jamonholmgren** [comment]
Ran into the same thing following the docs [here](https://github.com/infinitered/reactotron/blob/master/docs/plugin-track-global-errors.md#usage).
